package com.kaiyuan.dfb.mobilecenter.commons.constant;

/**
 * @author yangzhibin@che001.com
 * @date 2016/9/7
 */
public enum CodeMsgEnum {
    ERR_SRCUSER_IS_NOT_FOUND(ResultCode.PAYER_NOT_FOUND, "付款方不存在"),
    ERR_DESTUSER_IS_NOT_FOUND(ResultCode.RECEIVER_NOT_FOUND, "收款方不存在"),
    ERR_SRCSERVICEACCOUNT_IS_NOT_FOUND(ResultCode.PAYER_SERVICEACCOUNT_NOT_FOUND, "付款方服务未开通"),
    ERR_SHOPPINGORDER_PAYER_WAS_NOT_DONE_REAL_NAME_CHECKED(ResultCode.PAYER_NOT_REAL_CHECK, "付款方未实名认证"),
    ERR_SRCACCOUNT_IS_NOT_FOUND(ResultCode.PAYER_ACCOUNT_NOT_FOUND, "付款方账户不存在"),
    ERR_SRCCARD_IS_NOT_FOUND(ResultCode.PAYER_CARD_NOT_FOUND, "付款方银行卡不存在"),
    ERR_DESTSERVICEACCOUNT_IS_NOT_FOUND(ResultCode.ERR_DESTSERVICEACCOUNT_IS_NOT_FOUND, "收款方服务未开通"),
    ERR_SHOPPINGORDER_RECEIVER_WAS_NOT_DONE_REAL_NAME_CHECKED(ResultCode.ERR_SHOPPINGORDER_RECEIVER_WAS_NOT_DONE_REAL_NAME_CHECKED, "收款方未实名认证"),
    ERR_DESTCARD_IS_NOT_FOUND(ResultCode.ERR_DESTCARD_IS_NOT_FOUND, "收款方开元卡不存在"),
    ERR_DESTACCOUNT_IS_NOT_FOUND(ResultCode.ERR_DESTACCOUNT_IS_NOT_FOUND, "收款方账户不存在"),
    ERR_THE_TX_WITH_THE_REQUESTID_HAS_EXIST2(ResultCode.ERR_THE_TX_WITH_THE_REQUESTID_HAS_EXIST2, "订单已存在"),
    ERR_CREATE_TX_IS_NOT_SUCCESS(ResultCode.ERR_CREATE_TX_IS_NOT_SUCCESS, "下单保存订单失败"),
    ERR_CANNOT_TO_SAVE_RETURNURL(ResultCode.ERR_CANNOT_TO_SAVE_RETURNURL, "下单保存回调地址失败"),
    INTERNAL_SERVER_ERROR(ResultCode.INTERNAL_SERVER_ERROR, "服务器内部错误"),
    ERR_ORDERTX_IS_NOT_FOUND(ResultCode.ERR_ORDERTX_IS_NOT_FOUND, "订单不存在"),
    ERR_TX_NOT_FOUND(ResultCode.ERR_TX_NOT_FOUND, "交易不存在"),
    ERR_TX_NOT_PENDING_STATE(ResultCode.ERR_TX_NOT_PENDING_STATE, "交易状态不是进行中"),
    ERR_OTP_MAX_COUNT_EXCEEDED(ResultCode.ERR_OTP_MAX_COUNT_EXCEEDED, "已经超出OTP最大获取次数"),
    ERR_OTP_GET_AVAILABLE_FAILED(ResultCode.ERR_OTP_GET_AVAILABLE_FAILED, "获取可用OTP不存在"),
    ERR_OTP_MIN_REFRESH_TIME_NOT_PASSED(ResultCode.ERR_OTP_MIN_REFRESH_TIME_NOT_PASSED, "OTP获取太频繁"),
    ERR_OTP_OLD_CANCEL_FAILED(ResultCode.ERR_OTP_OLD_CANCEL_FAILED, "更新旧otp失败"),
    ERR_OTP_CREATION_FAILED(ResultCode.ERR_OTP_CREATION_FAILED, "创建otp失败"),
    ERR_OTP_NOT_FOUND(ResultCode.NOT_FOUND,"未找到OTP信息"),
    //ERR_TX_UPDATE_FAILED(ResultCode.ERR_TX_UPDATE_FAILED, "更新交易的otp获取次数失败"),
    ERR_RETURNURL_IS_NOT_FOUND(ResultCode.ERR_RETURNURL_IS_NOT_FOUND, "回调URL不存在"),
    ERR_DBPARENTTX_IS_NOT_FOUND(ResultCode.ERR_DBPARENTTX_IS_NOT_FOUND, "待支付的订单不存在"),
    ERR_INVALID_PAY_TYPEDETAIL_LENGTH_ERROR(ResultCode.ERR_INVALID_PAY_TYPEDETAIL_LENGTH_ERROR, "支付方式不合法"),
    ERR_INVALID_PAY_TYPEDETAIL_0_ERROR(ResultCode.ERR_INVALID_PAY_TYPEDETAIL_0_ERROR, "支付方式不合法"),
    ERR_INVALID_PAY_TYPEDETAIL_1_ERROR(ResultCode.ERR_INVALID_PAY_TYPEDETAIL_1_ERROR, "支付方式不合法"),
    ERR_INVALID_PAY_TYPEDETAIL_2_ERROR(ResultCode.ERR_INVALID_PAY_TYPEDETAIL_2_ERROR, "支付方式不合法"),
    INVALID_GETPAY_AMOUNTDETAIL0_IS_NULL(ResultCode.INVALID_GETPAY_AMOUNTDETAIL0_IS_NULL, "金额不合法"),
    INVALID_GETPAY_AMOUNTDETAIL1_IS_NULL(ResultCode.INVALID_GETPAY_AMOUNTDETAIL1_IS_NULL, "金额不合法"),
    INVALID_GETPAY_AMOUNTDETAIL2_IS_NULL(ResultCode.INVALID_GETPAY_AMOUNTDETAIL2_IS_NULL, "金额不合法"),
    ERR_INVALID_PAY_AMOUNTDETAIL_0_ERROR(ResultCode.ERR_INVALID_PAY_AMOUNTDETAIL_0_ERROR, "金额不合法"),
    ERR_INVALID_PAY_AMOUNTDETAIL_1_ERROR(ResultCode.ERR_INVALID_PAY_AMOUNTDETAIL_1_ERROR, "金额不合法"),
    ERR_INVALID_PAY_AMOUNTDETAIL_2_ERROR(ResultCode.ERR_INVALID_PAY_AMOUNTDETAIL_2_ERROR, "金额不合法"),
    ERR_KYPAYAMOUNT_OR_HEEPAYAMOUNT_OR_TOTALAMOUNT_IS_NOT_RIGHT(ResultCode.ERR_KYPAYAMOUNT_OR_HEEPAYAMOUNT_OR_TOTALAMOUNT_IS_NOT_RIGHT, "金额不合法"),
    ERR_ALL_CHILD_IS_NOT_EQUALS_PARENT(ResultCode.ERR_ALL_CHILD_IS_NOT_EQUALS_PARENT, "子交易交易金额和与父交易不一致"),
    ERR_ORDERPAY_GETOTP_IS_NULL(ResultCode.ERR_ORDERPAY_GETOTP_IS_NULL, "OTP为空"),
    ERR_THE_GIVEN_OTP_NOT_FOUND(ResultCode.ERR_THE_GIVEN_OTP_NOT_FOUND, "OTP不存在"),
    ERR_OTP_TIME_HAS_BEEN_GONE_30_MINUTES(ResultCode.ERR_OTP_TIME_HAS_BEEN_GONE_30_MINUTES, "OTP超时"),
    ERR_TODELETEOLDHEETX_ERROR(ResultCode.ERR_TODELETEOLDHEETX_ERROR, "删除旧网银支付的交易信息未成功"),
    ERR_ORDERPAYCREATE_SETTRANSDETAILWITHOLDNEEDRELEASE_ERROR(ResultCode.ERR_ORDERPAYCREATE_SETTRANSDETAILWITHOLDNEEDRELEASE_ERROR, "支付创建查询历史锁定数据处理失败"),
    AFAMOUNT_TOCREATENEWTXKYCOMPLETED_ERROR(ResultCode.AFAMOUNT_TOCREATENEWTXKYCOMPLETED_ERROR, "创建消费帐户支付的交易信息未成功"),
    //新加
    //1、服务开通项
    PAYER_ACCOUNTSERVICE_NULL(ResultCode.PAYER_SERVICEACCOUNT_NOT_FOUND, "付款用户服务未开通"),
    //2、用户user
    PAYER_USER_NULL(ResultCode.PAYER_NOT_FOUND, "付款用户信息不存在"),
    PAYER_USER_STATUS_ERR(ResultCode.PAYER_USER_STATUS_ERR, "付款用户状态异常"),
    PAYER_USER_NOT_SELF_ERR(ResultCode.PAYER_USER_NOT_SELF_ERR, "付款操作 当前登录人不是付款方"),
    PAYER_USER_RECEIVER_SELF_ERR(ResultCode.PAYER_USER_RECEIVER_SELF_ERR, "收款操作，付款方不能是自己"),
    //3、实名认证
    PAYER_USER_NOT_DO_NAMECHECK(ResultCode.PAYER_NOT_REAL_CHECK, "付款用户未经过实名认证"),
    //4、信息完整性
    PAYER_SERVICEACCOUNT_FULL_NAME_NOT_FOUND(ResultCode.PAYER_SERVICEACCOUNT_FULL_NAME_NOT_FOUND, "付款用户serviceAccount.fullName没有"),
    PAYER_STORE_NOT_FOUND(ResultCode.PAYER_STORE_NOT_FOUND, "付款用户store企业基本信息没有"),
    PAYER_STORE_NAME_NOT_FOUND(ResultCode.PAYER_STORE_NAME_NOT_FOUND, "付款用户企业名称没有"),
    //5、账户
    PAYER_ACCOUNT_NULL(ResultCode.PAYER_ACCOUNT_NOT_FOUND, "付款用户账户不存在"),
    PAYER_ACCOUNT_STATUS_ERR(ResultCode.PAYER_ACCOUNT_STATUS_ERR, "付款用户账户金额或状态异常"),
    PAYER_ACCOUNT_NOT_ACTIVATED(ResultCode.PAYER_ACCOUNT_NOT_ACTIVATED, "付款用户账户状态未激活"),
    PAYER_ACCOUNT_AMOUNT_LESS(ResultCode.PAYER_ACCOUNT_AMOUNT_LESS, "付款用户资金不足"),
    PAYER_ACCOUNT_AF_AMOUNT_LESS(ResultCode.PAYER_ACCOUNT_AF_AMOUNT_LESS, "付款用户AF资金不足"),
    PAYER_ACCOUNT_CF_AMOUNT_LESS(ResultCode.PAYER_ACCOUNT_CF_AMOUNT_LESS, "付款用户CF资金不足"),
    PAYER_ACCOUNT_QYD_AMOUNT_LESS(ResultCode.PAYER_ACCOUNT_QYD_AMOUNT_LESS, "付款用户轻易贷代扣资金不足"),
    //6、开元卡
    PAYER_CARD_NULL(ResultCode.PAYER_CARD_NOT_FOUND, "付款用户开元卡为空"),
    PAYER_CARD_NOT_ALLOWED(ResultCode.PAYER_CARD_NOT_ALLOWED, "付款用户开元卡状态不允许交易"),
    PAYER_CARD_CSC_ERR(ResultCode.PAYER_CARD_CSC_ERR, "付款操作，安全码不匹配"),

    /****
     * 收款用户
     ****/
//1、服务开通项
    RECEIVER_ACCOUNTSERVICE_NULL(ResultCode.ERR_DESTSERVICEACCOUNT_IS_NOT_FOUND, "收款用户服务未开通"),
    //2、用户user
    RECEIVER_USER_NULL(ResultCode.RECEIVER_NOT_FOUND, "收款用户信息不存在"),
    RECEIVER_USER_STATUS_ERR(ResultCode.RECEIVER_USER_STATUS_ERR, "收款用户状态异常"),
    RECEIVER_USER_RECEIVER_SELF_ERR(ResultCode.RECEIVER_USER_RECEIVER_SELF_ERR, "付款操作 收款人不能是自己"),
    RECEIVER_USER_RECEIVER_NOT_SELF_ERR(ResultCode.RECEIVER_USER_RECEIVER_NOT_SELF_ERR, "收款操作 登录人不是收款方"),
    //3、实名认证
    RECEIVER_USER_NOT_DO_NAMECHECK(ResultCode.ERR_SHOPPINGORDER_RECEIVER_WAS_NOT_DONE_REAL_NAME_CHECKED, "收款用户未经过实名认证"),
    //4、信息完整性
    RECEIVER_SERVICEACCOUNT_FULL_NAME_NOT_FOUND(ResultCode.RECEIVER_SERVICEACCOUNT_FULL_NAME_NOT_FOUND, "收款用户serviceAccount.fullName没有"),
    RECEIVER_STORE_NOT_FOUND(ResultCode.RECEIVER_STORE_NOT_FOUND, "收款用户store企业基本信息没有"),
    RECEIVER_STORE_NAME_NOT_FOUND(ResultCode.RECEIVER_STORE_NAME_NOT_FOUND, "收款用户企业名称没有"),
    //5、账户
    RECEIVER_ACCOUNT_NULL(ResultCode.ERR_DESTACCOUNT_IS_NOT_FOUND, "收款用户账户不存在"),
    RECEIVER_ACCOUNT_STATUS_ERR(ResultCode.RECEIVER_ACCOUNT_STATUS_ERR, "收款用户账户金额或状态异常"),
    RECEIVER_ACCOUNT_NOT_ACTIVATED(ResultCode.RECEIVER_ACCOUNT_NOT_ACTIVATED, "收款用户账户状态未激活"),
    //6、开元卡
    RECEIVER_CARD_NULL(ResultCode.ERR_DESTCARD_IS_NOT_FOUND, "收款用户开元卡为空"),
    RECEIVER_CARD_NOT_ALLOWED(ResultCode.RECEIVER_CARD_NOT_ALLOWED, "收款用户开元卡状态不允许交易"),

    /***
     * 交易订单
     ****/
    TRANS_ORDER_NULL(ResultCode.ERR_ORDERTX_IS_NOT_FOUND, "交易订单不存在"),
    TRANS_ORDER_TYPE_ERR(ResultCode.TRANS_ORDER_TYPE_ERR, "交易订单类型跟当前操作不匹配"),
    TRANS_ORDER_STATUS_ERR(ResultCode.TRANS_ORDER_STATUS_ERR, "交易订单状态错误"),
    TRANS_ORDER_CHILD_NULL(ResultCode.TRANS_ORDER_CHILD_NULL, "子交易订单为空"),
    TRANS_ORDER_AMOUNT_ERR(ResultCode.TRANS_ORDER_AMOUNT_ERR, "交易订单金额错误"),
    TRANS_ORDER_ILLEGAL_OPERATION(ResultCode.TRANS_ORDER_ILLEGAL_OPERATION, "用户非法订单操作"),
    TRANS_ORDER_ROYALTY_PARAMET_ERR(ResultCode.TRANS_ORDER_ROYALTY_PARAMET_ERR, "支付分户账参数错误"),
    TRANS_ORDER_USER_NOT_LOGGED(ResultCode.TRANS_ORDER_USER_NOT_LOGGED, "支付创建发起用户，跟当前交易初始化用户不一致"),

    ERR_PAYER_ACCOUNT_UPDATE_FAILED(ResultCode.ERR_PAYER_ACCOUNT_UPDATE_FAILED, "账务更新失败"),
    ERR_PAYER_CARD_UPDATE_FAILED(ResultCode.ERR_PAYER_CARD_UPDATE_FAILED, "开元卡更新失败"),
    ERR_TX_LOCKED_FUND_CREATION_FAILED(ResultCode.ERR_TX_LOCKED_FUND_CREATION_FAILED, "冻结资金创建失败"),
    ERR_TX_REVIEW_CREATION_FAILED(ResultCode.ERR_TX_REVIEW_CREATION_FAILED, "订单审核记录创建失败"),
    ERR_TX_UPDATE_FAILED(ResultCode.ERR_TX_UPDATE_FAILED,"支付订单更新失败"),

    ERR_TX_QYD_AMOUNT_ERROR(ResultCode.ERR_TX_QYD_AMOUNT_ERROR, "轻易贷返回余额格式有误"),
    ERR_TX_QYD_AMOUNT_LESS_ERROR(ResultCode.ERR_TX_QYD_AMOUNT_LESS_ERROR, "轻易贷余额不足"),

    APPROVE_LOGGED_USER_ERR(ResultCode.APPROVE_LOGGED_USER_ERR, "当前操作人非法"),
    APPROVE_TX_OTP_NULL(ResultCode.ERR_ORDERPAY_GETOTP_IS_NULL, "验证码错误"),
    APPROVE_TX_OTP_GONE(ResultCode.ERR_OTP_TIME_HAS_BEEN_GONE_30_MINUTES, "交易动态otp超时"),
    APPROVE_TX_OTP_PROCESS_ERR(ResultCode.APPROVE_TX_OTP_PROCESS_ERR, "交易动态otp验证异常"),

    APPROVE_ERR_PAYER_ACCOUNT_UPDATE_FAILED(ResultCode.APPROVE_ERR_PAYER_ACCOUNT_UPDATE_FAILED, "确认交易失败，更新付款账户失败"),
    APPROVE_ERR_PAYER_CARD_UPDATE_FAILED(ResultCode.APPROVE_ERR_PAYER_CARD_UPDATE_FAILED, "确认交易失败，更新付款开元卡失败"),
    APPROVE_ERR_RECEIVER_ACCOUNT_UPDATE_FAILED(ResultCode.APPROVE_ERR_RECEIVER_ACCOUNT_UPDATE_FAILED, "确认交易失败,更新收款账户失败"),
    APPROVE_ERR_RECEIVER_CARD_UPDATE_FAILED(ResultCode.APPROVE_ERR_RECEIVER_CARD_UPDATE_FAILED, "确认交易失败，更新收款开元卡失败"),
    APPROVE_ERR_TX_LOCKED_FUND_UPDATE_FAILED(ResultCode.APPROVE_ERR_TX_LOCKED_FUND_UPDATE_FAILED, "确认交易失败，更新订单 及 锁定资金失败"),
    APPROVE_ERR_TX_TRANSFERRED_FUND_PAYER_REGULAR_CREATION_FAILED(ResultCode.APPROVE_ERR_TX_TRANSFERRED_FUND_PAYER_REGULAR_CREATION_FAILED, "确认交易失败,记录付款方开元卡交易记录失败"),
    APPROVE_ERR_TX_TRANSFERRED_FUND_RECEIVER_REGULAR_CREATION_FAILED(ResultCode.APPROVE_ERR_TX_TRANSFERRED_FUND_RECEIVER_REGULAR_CREATION_FAILED, "确认交易失败，记录收款方开元卡交易记录失败"),
    APPROVE_ERR_TX_FOR_FEE_CREATION_FAILED(ResultCode.APPROVE_ERR_TX_FOR_FEE_CREATION_FAILED, "确认交易失败，记录收款方交易佣金流水失败"),
    APPROVE_ERR_TX_TRANSFERRED_FUND_RECEIVER_FEE_CREATION_FAILED(ResultCode.APPROVE_ERR_TX_TRANSFERRED_FUND_RECEIVER_FEE_CREATION_FAILED, "确认交易失败，记录收款方开元卡佣金流水失败"),
    APPROVE_ERR_TX_TRANSFERRED_FUND_AUTOCHINA_FEE_CREATION_FAILED(ResultCode.APPROVE_ERR_TX_TRANSFERRED_FUND_AUTOCHINA_FEE_CREATION_FAILED, "确认交易失败，记录平台卡佣金流水失败"),
    APPROVE_ERR_OTP_UPDATE_FAILED(ResultCode.APPROVE_ERR_OTP_UPDATE_FAILED, "确认交易失败，更新交易otp码失败"),
    APPROVE_ERR_TX_UPDATE_FAILED(ResultCode.APPROVE_ERR_TX_UPDATE_FAILED, "订单更新失败"),


    SPECIAL_PATCH_AMT_ERR(ResultCode.SPECIAL_PATCH_AMT_ERR, "违约用户代偿后门-代偿金额异常"),
    SPECIAL_PATCH_PHONE_ERR(ResultCode.SPECIAL_PATCH_PHONE_ERR, "违约用户代偿后门-港联账户不匹配"),
    SPECIAL_PATCH_VERIFYCODE_NULL(ResultCode.SPECIAL_PATCH_VERIFYCODE_NULL, "违约用户代偿后门-用户消费码不存在"),
    SPECIAL_PATCH_VERIFYCODE_ERR(ResultCode.SPECIAL_PATCH_VERIFYCODE_ERR, "违约用户代偿后门-填写消费码不匹配"),
    SPECIAL_PATCH_VERIFYCODE_USED(ResultCode.SPECIAL_PATCH_VERIFYCODE_USED, "违约用户代偿后门-消费码已使用"),


    //轻易贷接口调用
    QYD_API_ERR(ResultCode.QYD_API_ERR, "轻易贷接口调用出错了"),
    QYD_SEARCHUSERS_NULL(ResultCode.QYD_SEARCHUSERS_NULL, "轻易贷用户查询接口返回空"),
    QYD_SEARCHUSERS_NOT_EQUAL(ResultCode.QYD_SEARCHUSERS_NOT_EQUAL, "轻易贷用户查询接口返回数量与传入用户个数不一致"),
    QYD_UP_LIMIT(ResultCode.QYD_UP_LIMIT, "超出接口约定上限"),

    //港联密匙操作
    GANGLIAN_SECRET_UPDATE_ERR(ResultCode.GANGLIAN_SECRET_UPDATE_ERR, "港联密匙更新失败"),

    //代扣错误
    QYD_ORDER_FAILED(ResultCode.QYD_ORDER_FAILED, "轻易贷代扣失败，本交易已取消，请重新发起交易"),
    QYD_ORDER_DOING(ResultCode.QYD_ORDER_DOING, "交易处理中，请稍后重试"),
    ERR_TX_CREATION_FAILED(ResultCode.ERR_TX_CREATION_FAILED, "创建交易失败"),
    ErrObj(ResultCode.ErrObj,"系统异常丢失"),
    ERR_ACC_DUPLICATE_ACCOUNTING(ResultCode.ERR_ACC_DUPLICATE_ACCOUNTING, "重复记账"),

    //OTP
    ERR_TX_ID_MISSING(ResultCode.ERR_TX_NOT_FOUND, "交易不存在"),

    ERR_LOGGED_ID_MISSING(ResultCode.USER_ID_IS_NULL, "登录用户ID信息不存在"),

    ERR_TX_NOT_PURCHASE(ResultCode.ERR_TX_NOT_PURCHASE, "交易类型不对"),

    ERR_TX_NOT_INITIALIZED_STATE(ResultCode.ERR_TX_NOT_PENDING_STATE, "交易状态未初始化"),

    ERR_SOME_REQUEST_PARAMETER_IS_NULL(ResultCode.PARAM_ERROR,"必要参数为空"),

    //SDK
    //付款方收入额度不足
    PAYER_DOES_NOT_HAVE_ENOUGH_FUNDS_IN_HIS_ACCOUNT(ResultCode.PAYER_DOES_NOT_HAVE_ENOUGH_FUNDS_IN_HIS_ACCOUNT,"付款方收入额度不足"),
    THE_ACCOUNT_FOR_PAYER_IS_FORZEN_OR_DOES_NOT_HAVE_ENOUGH_FUNDS(ResultCode.THE_ACCOUNT_FOR_PAYER_IS_FORZEN_OR_DOES_NOT_HAVE_ENOUGH_FUNDS,"付款方冻结中"),
    DBSRCACCOUNT_GETCASHFUNDS_LESS_THAN_REDUCEAMOUNT(ResultCode.DBSRCACCOUNT_GETCASHFUNDS_LESS_THAN_REDUCEAMOUNT,"付款方现金帐户可用金额不足"),
    SRC_GETLOCKEDAVAILABLEFUNDS_IS_LESS_THAN_OLDNEEDRELEASEAFAMOUNTSUM(ResultCode.SRC_GETLOCKEDAVAILABLEFUNDS_IS_LESS_THAN_OLDNEEDRELEASEAFAMOUNTSUM,"付款方消费帐户冻结金额不足"),
    SRC_GETLOCKEDCASHFUNDS_IS_LESS_THAN_OLDNEEDRELEASECFAMOUNTSUM(ResultCode.SRC_GETLOCKEDCASHFUNDS_IS_LESS_THAN_OLDNEEDRELEASECFAMOUNTSUM,"付款方现金帐户冻结金额不足"),
    RECEIVER_ACCOUNT_IS_NOT_ALLOWED_TO_BE_USED_IN_A_TRANSACTION(ResultCode.RECEIVER_ACCOUNT_IS_NOT_ALLOWED_TO_BE_USED_IN_A_TRANSACTION,"收款方冻结收款中，不允许收款");

    CodeMsgEnum(Integer code, String msg) {
        this.code = code;
        this.msg = msg;
    }

    private Integer code;


    private String msg;

    public Integer getCode() {
        return code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }


    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }
}
